"""added updated_at column in stock table

Revision ID: 4c16cd0948b1
Revises: c61b58880bb0
Create Date: 2026-05-02 13:30:07.103793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c16cd0948b1'
down_revision: Union[str, Sequence[str], None] = 'c61b58880bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'updated_date')
    # ### end Alembic commands ###
