"""added customer table   and column 'country' in Item table

Revision ID: 5d8c322ba0da
Revises: 4c16cd0948b1
Create Date: 2026-05-04 16:44:16.315551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8c322ba0da'
down_revision: Union[str, Sequence[str], None] = '4c16cd0948b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('country', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_country'), 'items', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_country'), table_name='items')
    op.drop_column('items', 'country')
    # ### end Alembic commands ###
