"""added created_data column in customer table

Revision ID: d739659cb93b
Revises: 5d8c322ba0da
Create Date: 2026-05-04 16:54:05.925602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd739659cb93b'
down_revision: Union[str, Sequence[str], None] = '5d8c322ba0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'created_date')
    # ### end Alembic commands ###
